### ISSUE TITLE
Cannot find module 'fillper-plugin'

### ISSUE THREAD

**Issue by ArnabXD** [facebook/flipper#4100]
## 🐛 Bug Report

I have installed the latest flipper release (`0.165.0`) and all the plugins are unavailable. 

```
Plugin "XXXXX" failed to load, 'Cannot find module flipper-plugin .....'
```

It doesn't detect react-native ios/android apps either. 
However, it is working fine if I install `0.164.0`

![image](https://user-images.githubusercontent.com/52126165/190869439-08f5a1a7-1a5e-45ed-910a-b7a92ca2caaf.png)

![image](https://user-images.githubusercontent.com/52126165/190869433-379b7ebd-dcd8-41e1-a1a0-502b9447ae10.png)

### What I have Tried so far

- Reinstalling several times,
- Deleting `~/.flipper` directory

## To Reproduce

I dont know, but I found same issue on [stack-overflow](https://stackoverflow.com/questions/73749509/problem-with-plugin-of-flipper-version-0-165-0) created by someone else. (I copied the images from there, those were same for me as well)_

## Environment

PC : `Mac Air (M1, 2020)`

**Comment by adbs1** [comment]
Can confirm the same issue after upgrading from 0.164.0 to 0.165.0 on a 2020 macbook pro.

Downgrading for now...

**Comment by aestebancl1989** [comment]
Same is happening to me 
<img width="1063" alt="Screen Shot 2022-09-18 at 11 01 30" src="https://user-images.githubusercontent.com/79030846/190919309-51106732-94d8-40f8-b899-f53aca283425.png">

**Comment by meetajhu** [comment]
i really doubt the flipper releaser's testing strategy before releasing a new version. At least remove the annoying popup when a new version is available.

**Comment by pnthach95** [comment]
Literally everything isn't working right now.

Search on website is dead
<img width="1177" alt="Screen Shot 2022-09-19 at 10 00 55 AM" src="https://user-images.githubusercontent.com/31266357/190943233-c46dabe4-3899-421d-8898-f10db1ad4016.png">

My desktop plug-in refuses to work without giving any reason/logs

**Comment by affansk** [comment]
even i am facing after upgrading to 0.165.0

**Comment by tunm1228** [comment]
I have the same error as you

**Comment by arayhan** [comment]
me as well, is there any solution other than downgrade?

**Comment by kkureli** [comment]
same

**Comment by kkureli** [comment]
the problem is about v0.165.0, I downloaded v.0.164.0 from https://github.com/facebook/flipper/releases/tag/v0.164.0

And it works

**Comment by irmakcosarsahna** [comment]
same isseue

**Comment by irmakcosarsahna** [comment]
same issue

**Comment by aigoncharov** [comment]
@ArnabXD could you attach Flipper logs? 
![image](https://user-images.githubusercontent.com/12794628/191098094-37a5bb6d-dc3f-4632-9a9a-7a3a9e21953b.png)

**Comment by aigoncharov** [comment]
Found the root cause. Pushing out a new release tomorrow. Sorry for the inconvenience.

**Comment by aigoncharov** [comment]
In the meantime, you can try enabling "Server (Experimental)" in the settings as a workaround. Weirdly enough, it fixes the issue.
![image](https://user-images.githubusercontent.com/12794628/191126452-95e3408f-5fe3-4bf5-aa73-32c9efdbc714.png)

**Comment by OmkarArora** [comment]
Got the 0.165.1 update, still not working for me
![image](https://user-images.githubusercontent.com/42699828/191185397-5a67c078-10e4-4936-81b9-0d2b9b7888ae.png)

**Comment by aigoncharov** [comment]
Should be fixed by 8716761cb3e694343d9f41083f138072ddaf404f. Included in 0.166

**Comment by Pandazaur** [comment]
Confirmed ! v0.166 fixes it

**Comment by wuhui2023** [comment]
I get the same issue, who resolve it, share your way please.
