### ISSUE TITLE
Discussion: Folly use of an OpenSSL pod that is built with bitcode turned on

### ISSUE THREAD

**Issue by davidmcraejr** [facebook/flipper#485]
Thoughts on switching to using a pod that includes bitcode support for OpenSSL which is a dependency of Folly such as openssl-ios-bitcode

Side note: anyone know which repo Follys podspec originates from?

**Comment by priteshrnandgaonkar** [comment]
Folly podspec's definition is [here](https://github.com/facebook/flipper/blob/master/iOS/Podspecs/Flipper-Folly.podspec). The source code to which it refers to is [this](https://github.com/facebook/flipper/blob/master/iOS/Podspecs/Flipper-Folly.podspec).


Let me try using openssl-ios-bitcode

**Comment by dmac81** [comment]
Thanks @priteshrnandgaonkar!

**Comment by matt-oakes** [comment]
This shouldn't have been closed. The `OpenSSL-Universal` pod contains a pre-compiled binary which does not support Bitcode. Therefore, if you want to build for real devices and have Flipper integrated, you can't have Bitcode enabled.

**Comment by CooCooCaCha** [comment]
Please reopen, this is still an issue. I cannot debug on-device with react-native right now.

**Comment by mikehardy** [comment]
Confirmed - this is starting to surface as support issues in other repositories - https://github.com/invertase/react-native-firebase/issues/3384 - @priteshrnandgaonkar please reopen

**Comment by mikehardy** [comment]
For affected react-native people - @matt-oakes - I turned bitcode off in debug builds and it worked, and I kept it on for release mode builds and sent it to TestFlight, it seems to work fine, so there's a workaround for now that seems to work okay

**Comment by Benzer1406** [comment]
Turning off Bitcode in debug builds triggered a lot of Swift Code errors. Please reopen and provide a fix.

**Comment by unfrgivn** [comment]
I apologize for my ignorance on how React Native / Flipper / Folly are all tied together but this was just merged yesterday and possibly solves this issue without having to disable bitcode? krzyzanowskim/OpenSSL#83 into `1.0.2.20`

The folly pod is locked to `1.0.2.19` so I did not patch the podspecs and test if it resolves the Xcode build issue or not.

**Comment by mikehardy** [comment]
@unfrgivn I proposed this based on your comment, we'll see https://github.com/facebook/flipper/pull/1171

**Comment by priteshrnandgaonkar** [comment]
I will check if updating the openssl dependency solves the bitcode issue.

**Comment by priteshrnandgaonkar** [comment]
I tried using the latest openssl dependency with bitcode set to enabled.I got the following error

```
Undefined symbols for architecture x86_64:
  "___darwin_check_fd_set_overflow", referenced from:
      _RAND_poll in libcrypto.a(rand_unix.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by priteshrnandgaonkar** [comment]
We depend on OpenSSL, unless we get the

**Comment by chrisbobbe** [comment]
@stale bot please go away—there's been recent activity on this in https://github.com/facebook/flipper/pull/1171.

**Comment by mweststrate** [comment]
> @Stale bot please go away—there's been recent activity on this in #1171.

🤯

**Comment by eggybot** [comment]
I can confirm that this issue still showing for RN v0.63.2, please note if I'm using a Simulator in `Debug` the result was success without any error. But if I test it in an actual iPhone device (model 7, 8, 11) this error exist.

**Comment by justinjoyn** [comment]
Running into this after I updated Xcode to v12.
```
ld: in /Users/user/Projects/example/ios/Pods/OpenSSL-Universal/ios/lib/libcrypto.a(cryptlib.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/user/Projects/example/ios/Pods/OpenSSL-Universal/ios/lib/libcrypto.a' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
On `"react-native": "0.62.2"`

**Comment by maxammann** [comment]
@justinjoyn I think that is not related. This issue is about missing bitcode in a specific openssl release

**Comment by Gurpreetgpsingh** [comment]
> I tried using the latest openssl dependency with bitcode set enabled and disabled, but, I got the following error. Seems like the latest binary doesn't have all the symbols.
> 
> ```
> Undefined symbols for architecture x86_64:
>   "___darwin_check_fd_set_overflow", referenced from:
>       _RAND_poll in libcrypto.a(rand_unix.o)
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ```

Am also facing this issue in react native 0.63.3 and Xcode 11.3
Please let me know if anyone having any clue

**Comment by Mandy-1989** [comment]
I m also facing this similar issue

**Comment by arun-es** [comment]
On Mojave, I am exploring upgrading Xcode to 11.7. If this works, I will update you.

**Comment by arun-es** [comment]
I can now confirm this works. It solved my problem.
https://stackoverflow.com/a/61013836/2940495

**Comment by mweststrate** [comment]
We're about to land an openSSL bump / bitcode fix, so should be solved by
next weeks version

**Comment by ghasemikasra39** [comment]
I am facing:
```
Undefined symbols for architecture x86_64:
  "___darwin_check_fd_set_overflow", referenced from:
      _RAND_poll in libcrypto.a(rand_unix.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

after upgrade to `0.63.3`. Any solution?

**Comment by Gurpreetgpsingh** [comment]
> I am facing:
> 
> ```
> Undefined symbols for architecture x86_64:
>   "___darwin_check_fd_set_overflow", referenced from:
>       _RAND_poll in libcrypto.a(rand_unix.o)
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ```
> 
> after upgrade to `0.63.3`. Any solution?

I updated Xcode from 11.3 to 11.7 
then issue is fixed

**Comment by developius** [comment]
Upgrading to Xcode 11.7 fixed it for me too (RN v0.63.3).

**Comment by ghasemikasra39** [comment]
Upgrading to Xcode 12 fixed it for me

**Comment by mikehardy** [comment]
Upgrading to Xcode did nothing - what happened is they released a fix in their podspecs to similar to PR worked through here https://github.com/facebook/flipper/pull/1171 - it's resolved now via effort not magic ;-)

**Comment by paolorr** [comment]
> Upgrading to Xcode did nothing - what happened is they released a fix in their podspecs to similar to PR worked through here #1171 - it's resolved now via effort not magic ;-)

@mikehardy I'm using Mohave 10.14.6 and XCode 11.0. Does this PR has to do with latest versions of XCode? Because with Flipper-Folly 2.3.0 I get the `___darwin_check_fd_set_overflow` error but if I revert to 2.2.0 it works with Xcode 11.0

**Comment by mikehardy** [comment]
I don't know, given Apple requires you support their latest mobile operating system APIs, and the newer Xcode versions are required to do so, I can't imagine not using current stable Xcode, so I haven't tested 11 since 12 came out, and don't see the utility of doing so?

**Comment by skheirandish** [comment]
Im having the same issue as of today.

**Comment by lzhlewis2015** [comment]
> > I tried using the latest openssl dependency with bitcode set enabled and disabled, but, I got the following error. Seems like the latest binary doesn't have all the symbols.
> > ```
> > Undefined symbols for architecture x86_64:
> >   "___darwin_check_fd_set_overflow", referenced from:
> >       _RAND_poll in libcrypto.a(rand_unix.o)
> > ld: symbol(s) not found for architecture x86_64
> > clang: error: linker command failed with exit code 1 (use -v to see invocation)
> > ```
> 
> Am also facing this issue in react native 0.63.3 and Xcode 11.3
> Please let me know if anyone having any clue

I also facing the same issue with you

**Comment by gustavoarsantos** [comment]
Only can solve the problem, who can update Xcode to 11.7?

**Comment by muz786** [comment]
@mikehardy Does this fix work for macOS Mojave Xcode 11.3? or i have to update to macOS Catalina and install 11.7?

**Comment by mikehardy** [comment]
I believe the general rule is that if you develop things for apple platforms you use the most up to date Xcode
I believe Xcode 12 is required to support iOS14 features, for instance, and some of them (like permissions they added/changed) are required if you touch them. Which is a long-ish way of saying I don't really know, I use up to date Xcode as a matter of course and forward-port to required changes in order to avoid unexpected app store rejections

**Comment by ronilitman** [comment]
@mweststrate Hi, any news regarding the new version that should solve this issue?
Thank you :)

**Comment by mikehardy** [comment]
It's released, this is not a problem anymore.

**Comment by numandev1** [comment]
you can try these solutions https://stackoverflow.com/questions/29082174/ios-xcode-build-failing-due-to-openssl/76455587#76455587
