### ISSUE TITLE
[iOS] use_framework!

### ISSUE THREAD

**Issue by bolismauro** [facebook/flipper#254]
I'm trying to install the flipper pod in a repository where swift pods are added to the project using the `use_framework!` option.

Unfortunately, this triggers an error that prevents the installation from completing successfully.

```
[!] The 'Pods-ProjectName' target has transitive dependencies that include static binaries: 
(/path/to/Pods/CocoaLibEvent/lib/libevent.a,
/path/to/Pods/CocoaLibEvent/lib/libevent_core.a, 
/path/to/Pods/CocoaLibEvent/lib/libevent_extra.a,
/path/to/Pods/CocoaLibEvent/lib/libevent_pthreads.a,
/path/to/Pods/OpenSSL-Static/lib-ios/libcrypto.a, and
/path/to/Pods/OpenSSL-Static/lib-ios/libssl.a)
```

I cannot remove that option for some reasons. The most important one is a bug in Cocoapods
https://github.com/CocoaPods/CocoaPods/issues/7585

Since all the involved pods come from flipper, Is there something that we can do about it?

**Comment by priteshrnandgaonkar** [comment]
Cocoapod 1.5.0 supports static swift libraries. Since our pod depends on static libraries, using `use_framework1` may not work. May be replacing static libraries for Libevent and Openssl with dynamic may solve the issue. We are happy to have a PR from the community with regards to this,

**Comment by amleszk** [comment]
Is there any work around for this? looks like the dependency 'Folly' which uses 'CocoaLibEvent' is the problem. blocker for any iOS project that uses Swift.

https://github.com/facebook/folly/tree/master/folly
https://github.com/e314521/CocoaLibEvent

**Comment by dmac81** [comment]
Has anyone figured this out?  I've tried a few different ways to get this to work to no avail...

**Comment by dmac81** [comment]
Ok after playing around some more I have included this code in my Podfile and this works -

```
$static_framework = ['FlipperKit', 'Flipper', 'Folly', 
    'CocoaAsyncSocket', 'ComponentKit', 'DoubleConversion', 
    'glog', 'PeerTalk', 'RSocket', 'Yoga', 'YogaKit', 
    'CocoaLibEvent', 'OpenSSL-Static', 'boost-for-react-native']
```

```
pre_install do |installer|
    installer.pod_targets.each do |pod|
        if $static_framework.include?(pod.name)
            pod.host_requires_frameworks = false
        end
    end
end
```

This will cause Pods to build the pods in the array as static and the others dynamic frameworks

**Comment by GauravT9l** [comment]
Above thing is still not working of me, i am still getting below error 

> `undefined method `host_requires_frameworks=' for <Pod::PodTarget name=ComponentKit >:Pod::PodTarget`

**Comment by lijy91** [comment]
I got the same error, @dmac81  solution not working for me

```
[!] The 'Pods-Runner' target has transitive dependencies that include static binaries: (/Users/lijy91/Documents/Projects/blankapp/flutter_flipperkit/example/ios/Pods/CocoaLibEvent/lib/libevent.a, /Users/lijy91/Documents/Projects/blankapp/flutter_flipperkit/example/ios/Pods/CocoaLibEvent/lib/libevent_core.a, /Users/lijy91/Documents/Projects/blankapp/flutter_flipperkit/example/ios/Pods/CocoaLibEvent/lib/libevent_extra.a, /Users/lijy91/Documents/Projects/blankapp/flutter_flipperkit/example/ios/Pods/CocoaLibEvent/lib/libevent_pthreads.a, /Users/lijy91/Documents/Projects/blankapp/flutter_flipperkit/example/ios/Pods/OpenSSL-Static/lib-ios/libcrypto.a, and /Users/lijy91/Documents/Projects/blankapp/flutter_flipperkit/example/ios/Pods/OpenSSL-Static/lib-ios/libssl.a)
```

**Comment by DDDrop** [comment]
> Above thing is still not working of me, i am still getting below error
> 
> > `undefined method `host_requires_frameworks=' for <Pod::PodTarget name=ComponentKit >:Pod::PodTarget`

CocoaPods 1.6.0+ `host_requires_frameworks` is changed to be *readonly*

**Comment by dmac81** [comment]
@DDDrop good catch, here is the commit where they made that change:

https://github.com/CocoaPods/CocoaPods/commit/f7009cf7de0a96602a93b188c0d1e389ac180436#diff-8c725e5a3b8317f479af06a7eb820320

So this would only work on releases before 1.6.0.  When I get some time I will see if there is another way around this in 1.6.0 and above.

**Comment by priteshrnandgaonkar** [comment]
I tried the following

```
  pre_install do |installer|
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
    installer.pod_targets.each do |pod|
      if $static_framework.include?(pod.name)
        pod.instance_variable_set(:@host_requires_frameworks, false)
      end
    end
  end
```

It successfully generates the project, but the app fails to build. CocoaPod version used is 1.6.1

**Comment by dmac81** [comment]
I switched to using this:

```
  pre_install do |installer|
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
  
  installer.pod_targets.each do |pod|
    if $static_framework.include?(pod.name)
      
      def pod.host_requires_frameworks=(hostRequiresFrameworks)
        @host_requires_frameworks = hostRequiresFrameworks
      end
    
      pod.host_requires_frameworks = false
    end
  end
end
```

Which I know is an utter hack but it is deploying to a Simulator and connecting to Flipper Desktop with CocoaPods 1.6.0

Will try @priteshrnandgaonkar solution when I get a chance

**Comment by bpoplauschi** [comment]
Update for CP 1.7+ - I tried @dmac81's solution, but it didn't work (all frameworks were still built as dynamic). What worked for me was
```ruby
pre_install do |installer|
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
  installer.pod_targets.each do |pod|
    if $static_framework.include?(pod.name)
      def pod.build_as_static_framework?;
        true
      end
    end
  end
end
```
For previous CP versions, you can use the same approach (just replace `build_as_static_framework` with `static_framework` which got deprecated in CP 1.7 - https://www.rubydoc.info/gems/cocoapods/Pod/Target:static_framework%3F).

**Comment by priteshrnandgaonkar** [comment]
For CP 1.7+ Objective-C The following worked on the sample app with `use_framework!`

```
  $static_framework = ['FlipperKit', 'Flipper', 'Flipper-Folly',
    'CocoaAsyncSocket', 'ComponentKit', 'DoubleConversion',
    'glog', 'Flipper-PeerTalk', 'Flipper-RSocket', 'Yoga', 'YogaKit',
    'CocoaLibEvent', 'openssl-ios-bitcode', 'boost-for-react-native']

  pre_install do |installer|
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
    installer.pod_targets.each do |pod|
        if $static_framework.include?(pod.name)
          def pod.build_type;
            Pod::Target::BuildType.static_library
          end
        end
      end
  end
```

**Comment by kaushal9678** [comment]
I fixed this issue like following while using `react-native-firebase` for iOS app

```
platform :ios, '11.0'
 // new way to define use_frameworks! 
use_frameworks! :linkage => :static
```
For Flipper I used this one

```
$static_framework = ['FlipperKit', 'Flipper', 'Folly', 
    'CocoaAsyncSocket', 'ComponentKit', 'DoubleConversion', 
    'glog', 'PeerTalk', 'RSocket', 'Yoga', 'YogaKit', 
    'CocoaLibEvent', 'OpenSSL-Static', 'boost-for-react-native','Flipper-Fmt']
    pre_install do |installer|
    installer.pod_targets.each do |pod|
        if $static_framework.include?(pod.name)
           # pod.host_requires_frameworks = false
           def pod.build_type;
                Pod::BuildType.static_library
            end
        end
    end
end



```
