### ISSUE TITLE
macos 14.3.1 xcode 15.3 'facebook::flipper::SocketCertificateProvider' (aka 'int') is not a function or function pointer

### ISSUE THREAD

**Issue by krmao** [facebook/flipper#5500]
## 🐛 Bug Report
after upgrade macos to 14.3.1, and xcode to 15.3, xcode build react native 0.72.4 with error

***Called object type 'facebook::flipper::SocketCertificateProvider' (aka 'int') is not a function or function pointer***

also have a apple bug report [https://forums.developer.apple.com/forums/thread/747552](https://forums.developer.apple.com/forums/thread/747552)

## To Reproduce
upgrade macos to 14.3.1
upgrade xcode to 15.3
xcode build react-native 0.72.4 project

## Environment
macos 14.3.1
xcode 15.3
react-native 0.72.4

## Quick Fix
> midify FlipperTransportTypes.h and add bellow code to line 11

```
#include <functional>
```

**Comment by nstr** [comment]
Same problem

**Comment by tboba** [comment]
Hi there, I believe this issue is already fixed, since [this](https://github.com/facebook/flipper/commit/b3dcdb87f930dbbc9dbacb53ad60996e0111e7d8) commit is already on main (I can see this import in the newest release of Flipper as well).
Because of that, I'd suggest to move the discussion of this error to the React Native repo (there are already some [issues](https://github.com/facebook/react-native/issues/43335) that addresses this error).

**Comment by krmao** [comment]
thanks, now we can't use 0.248.0 [https://github.com/facebook/flipper/issues/5486](https://github.com/facebook/flipper/issues/5486)

```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled(["Debug"], { 'Flipper' => '0.248.0' })

```

```
[!] CocoaPods could not find compatible versions for pod "FlipperKit":
  In Podfile:
    FlipperKit (= 0.248.0)

None of your spec sources contain a spec satisfying the dependency: `FlipperKit (= 0.248.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

**Comment by krmao** [comment]
there is so many errors @tboba  [https://github.com/facebook/flipper/actions/workflows/publish-pods.yml](https://github.com/facebook/flipper/actions/workflows/publish-pods.yml)

**Comment by tboba** [comment]
@krmao Looks like Xcode has some issues with compiling the library. Unfortunately I can't do much, since I'm not the maintainer of Flipper 😅 But I see that there are issues with publishing it, since 0.233.0 version - https://cocoapods.org/pods/Flipper

**Comment by krmao** [comment]
Thanks for the reply, @tboba. Now I found a valid fix. Happy coding! [https://github.com/facebook/react-native/issues/43335#issuecomment-1982794252](https://github.com/facebook/react-native/issues/43335#issuecomment-1982794252)

**Comment by johnny-washswat** [comment]
We also solved by adding this into Podfile. You don't need to apply this fix every time

` installer.pods_project.targets.each do |target|
      if target.name == 'Flipper'
        file_path = 'Pods/Flipper/xplat/Flipper/FlipperTransportTypes.h'
        contents = File.read(file_path)
        unless contents.include?('#include <functional>')
          File.chmod(0755, file_path)
          File.open(file_path, 'w') do |file|
            file.puts('#include <functional>')
            file.puts(contents)
          end
        end
      end
    end
  end
end`
